### 1. Buatlah Tensor dibawah ini dengan Python:

$$ \begin{bmatrix} \begin{bmatrix} 23 & 50 \\ 7 & 12 \ \end{bmatrix} \begin{bmatrix} 57 & 67 \\ 99 & 43 \end{bmatrix} \\\\ \begin{bmatrix} 75 & 21 \\ 57 & 12 \ \end{bmatrix} \begin{bmatrix} 87 & 26 \\ 18 & 84 \end{bmatrix} \end{bmatrix} $$

In [3]:
import numpy as np
soal_1 = np.array(
    [
        [
            [
                [23,50],[7,12]
            ],
            [
                [57,67], [99,43]
            ],
            [
                [75,21], [57,12]
            ],
            [
                [87,26], [18,84]
            ]
        ]
    ]
)
soal_1

array([[[[23, 50],
         [ 7, 12]],

        [[57, 67],
         [99, 43]],

        [[75, 21],
         [57, 12]],

        [[87, 26],
         [18, 84]]]])

In [4]:
soal_1.shape

(1, 4, 2, 2)

### 2. Lakukan perkalian terhadap matrix berikut:

$$ A = \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix}\,, B = \begin{bmatrix} 17 \\ 22 \\ 19 \end{bmatrix} $$

In [7]:
#membuat matrix A dan B
A = np.array([[23,50,19], [7,12,109], [57,67,98]]) # 3 baris 3 kolom
B = np.array([17,22,19]) # 1 baris 3 kolom
print(f'Matriks A: \n{A}\n')
print(f'Matriks B: {B}')

Matriks A: 
[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]

Matriks B: [17 22 19]


In [14]:
#perkalian matrix
B.dot(A)

array([1628, 2387, 4583])

### 3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

$$ A = \begin{bmatrix} 23 & 50 & 19 \\ 7 & 12 & 109 \\ 57 & 67 & 98 \end{bmatrix} $$

In [15]:
#membuat matrix A
A = np.array([[23,50,19], [7,12,109], [57,67,98]])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [16]:
#melakukan transpose pada matrix A
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [17]:
#hitung determinan matrix A
np.linalg.det(A)

131344.0000000002

In [18]:
#hitung inverse matrix A
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])